version: '3'

networks:
  netw:
    driver: bridge

services:

  graphdb:
    image: ontotext/graphdb:10.4.1
    container_name: graphdb
    ports:
      - 7200:7200
    #volumes:
    #  - ./graphdb-data:/opt/graphdb/home    
    environment:
      - GDB_HEAP_SIZE=4g
      - GDB_OPTS=-Dgraphdb.workbench.cors.enable=true
      #- graphdb.security.auth.type=preemptive
      #- graphdb.security.auth.master-user=<username>
      #- graphdb.security.auth.master-password=<password>
    networks:
      - netw

  identity_api:
    build:
      context: ./src/IdentityAPI
      dockerfile: Dockerfile
    container_name: identity_api
    networks:
    - netw
    ports:
    - "1415:80"
    depends_on:
    - mssql_server_idapi

  web_app:
    build:
      context: ./src/WebAPP
      dockerfile: Dockerfile
    container_name: web_app
    networks:
    - netw
    ports:
    - "1416:80"
    depends_on:
    - identity_api

  data_manager_api:
    build:
      context: ./src/DataManagerAPI
      dockerfile: Dockerfile
    container_name: data_manager_api
    networks:
    - netw
    ports:
    - "1417:7777"
    depends_on:
    - graphdb

  mssql_server_idapi:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server_idapi
    environment:
      SA_PASSWORD: "YourPassword1!"
      ACCEPT_EULA: "Y"
    networks:
    - netw
    # for local debugging
    #ports:
    #  - "1433:1433"